# Generated by Django 3.1 on 2020-08-28 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование еденицы измерения', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование задачи', max_length=150)),
                ('describe', models.TextField(blank=True, help_text='Введите описание задачи (не обязательно)', max_length=400)),
                ('count', models.PositiveSmallIntegerField(blank=True, help_text='Введите количество затраченного времени')),
                ('sum', models.PositiveSmallIntegerField(help_text='Введите сумму')),
                ('date_of_task', models.DateField(auto_now=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.units')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_task_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.PositiveSmallIntegerField(blank=True, help_text='Введите стомость работы по умолчаниюза еденицу')),
                ('unit', models.ForeignKey(help_text='Выберите еденицу измерения работ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.units')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование клиента', max_length=100)),
                ('inn', models.CharField(blank=True, help_text='Введите ИНН клиента(не обязательно)', max_length=12, unique=True)),
                ('tel', models.CharField(blank=True, help_text='Введите телефон клиента(не обязательно)', max_length=16)),
                ('email', models.EmailField(blank=True, help_text='Введит email (не обязательно)', max_length=254)),
                ('cost', models.PositiveSmallIntegerField(blank=True, help_text='Введите стомость работы по умолчаниюза еденицу')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.units')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
