# Generated by Django 3.1 on 2020-08-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
